### ISSUE TITLE
dll import lib not created

### ISSUE THREAD

**Issue by ulrichard** [cpp-netlib/cpp-netlib#464] opened 2014-11-04 11:32 UTC
I try to compile cpp-netlib as shared libs using the following command:

cmake -G "Visual Studio 12 2013" ^
	-D CMAKE_INSTALL_PREFIX:PATH=%WORKSPACE%/msvc12_32 ^
	-D BOOST_ROOT:PATH=%EXTERNALSDIR%/boost/%BOOSTVER% ^
	-D BOOST_INCLUDEDIR:PATH=%EXTERNALSDIR%/boost/%BOOSTVER% ^
	-D BOOST_LIBRARYDIR:PATH=%EXTERNALSDIR%/boost/%BOOSTVER%/msvc12_32_dll ^
	-D Boost_USE_DEBUG_PYTHON:BOOL=ON ^
	-D Boost_USE_STATIC_LIBS:BOOL=OFF ^
	-D CPP-NETLIB_BUILD_SHARED_LIBS:BOOL=ON ^
	..
cmake --build . --config RelWithDebInfo --target INSTALL

To get around the first errors about boost::optional, I applied one of the workarounds that I found here.

Then I get a linker error that it cannot find cppnetlib-uri.lib. And indeed, the directory contains dll, pdb and ilk fines, but no lib files. I compared the project settings with one of our dll projects, and couldn't find the reason.  Linker->Advanced->ImportLibrary contains a valid path in the same directory as the dll and pdb files are generated, but the lib files is missing.

**Comment by WilliamTambellini** [comment] 2015-09-01 15:55
Hi guys,
I do confirm: trying to create dll through
cmake -DCPP-NETLIB_BUILD_SHARED_LIBS=ON
does generate 3 dlls but :  
- these dll are super small (few kb) aka do not contain the real cppnetlib algos/codes
- no interface .lib are generated
Does anyone know if adding dll build support is planned in the near futur ?
Cheers

**Comment by deanberris** [comment] 2015-09-02 23:26
@WilliamTambellini I think we do want to support this, but I don't know how to do this (I don't use Windows). Do you mind checking to see whether 0.11.2 fixes this?

**Comment by WilliamTambellini** [comment] 2015-09-03 07:40
Hi Dean, 
just like @ulrichard stated, to do this would just need to add some "__declspec(dllexport)" to the public API of cppnetlib usually through some macros, probably called something like  "BOOST_NETLIB_DECL". 
Boost is doing such way in the auto_link.hpp headers considering XXX is the name of the "module":

#ifdef BOOST_HAS_DECLSPEC
    #if defined(BOOST_ALL_DYN_LINK) || defined(BOOST_XXX_DYN_LINK)
        #if defined(BOOST_XXX_SOURCE)
            #define BOOST_XXX_DECL __declspec(dllexport)
        #else
            #define BOOST_XXX_DECL __declspec(dllimport)
        #endif
    #endif
#endif

I have quickly searched cppnetlib master but did nt see any.
Cheers
W.

**Comment by deanberris** [comment] 2015-09-11 13:51
Yes, we should do this in 0.11-devel (and release a 0.11.3 that does this properly).

If you can send me a pull request @WilliamTambellini I'd really appreciate that.

**Comment by WilliamTambellini** [comment] 2015-11-21 16:42
Hi,
On my side, I m ok with static linking and I mainly work under Linux so I won't probably implement this one.
Cheers
W.

**Comment by WilliamTambellini** [comment] 2015-11-23 23:00
By the way it's not a bug, just a feature that has not been implemented. 
It is possible to generate cpp netlib dynamic libs under Linux (.so), but not currently under Windows (.dll). 
@deanberris : this one is probably closeable.

**Comment by deanberris** [comment] 2015-11-24 09:27
Okay, but I don't understand what the requirement is on Windows to make this happen -- is this some code that needs to be inserted in the correct places as a macro, so that on Windows we export the symbols made part of the .dll?

**Comment by WilliamTambellini** [comment] 2015-11-24 15:03
yes : the best is a to create a macro, called for example  NETLIB_DECL, that would be empty under Linux/Mac.

**Comment by glynos** [comment] 2016-06-14 19:29
If it's closable, I'll close it now.

**Closed by glynos** 2016-06-14 19:29 UTC
Labels: BUG, Windows
