### ISSUE TITLE
Stuck at fetching response body

### ISSUE THREAD

**Issue by robin92** [cpp-netlib/cpp-netlib#493] opened 2015-02-01 09:32 UTC
The library seems not to work whatsoever. The following example ([wget](http://cpp-netlib.org/0.11.1/examples/http/simple_wget.html)):
```cpp
#include <boost/network/protocol/http/client.hpp>
#include <boost/network/uri.hpp>
#include <string>
#include <fstream>
#include <iostream>

namespace http = boost::network::http;
namespace uri = boost::network::uri;

namespace {
std::string get_filename(const uri::uri &url) {
    std::string path = uri::path(url);
    std::size_t index = path.find_last_of('/');
    std::string filename = path.substr(index + 1);
    return filename.empty()? "index.html" : filename;
}
} // namespace

int
main(int argc, char *argv[]) {
    if (argc != 2) {
        std::cerr << "Usage: " << argv[0] << " url" << std::endl;
        return 1;
    }

    try {
        http::client client;
        http::client::request request(argv[1]);
        http::client::response response = client.get(request);

        std::string filename = get_filename(request.uri());
        std::cout << "Saving to: " << filename << std::endl;
        std::ofstream ofs(filename.c_str());
        ofs << static_cast<std::string>(body(response)) << std::endl;
    }
    catch (std::exception &e) {
        std::cerr << e.what() << std::endl;
        return 1;
    }

    return 0;
}
```
stucks when calling ``body(response)``. Using Python builtin HTTP server it can also be verified that no HTTP request is sent - a timeout must be added to force sending a request but the library is still stuck on the same expression.

**Comment by deanberris** [comment] 2015-02-02 00:20
What version of the library are you using, which compiler, on which platform, using what version of Boost?

**Comment by robin92** [comment] 2015-02-04 17:19
@deanberris 
cpp-netlib 0.11.1-1
GCC 4.9.2
Linux x86_64 (Arch Linux)
Boost 1.57.X

**Comment by deanberris** [comment] 2015-02-04 22:33
There's a couple of things:

1. Add the "Connection: close" header to the request. This will instruct the server to close the connection down and not hold the socket open. The client doesn't by default set this header, because it also allows you to do incremental body parsing. To do this you want something like:

    request << header("Connection", "close");

2. Your client object is inside the try block. If anything threw inside that block, it would cause the client object to get destroyed and therefore wait on connections to get closed down. Moving the client object outside the try block will help you in that case.

Try those and let me know how it goes @robin92?

**Comment by robin92** [comment] 2015-02-21 09:51
First of all, sorry it took so long.

Unfortunately, the issue is persistent even after the ``header`` has been added and ``try-catch`` removed. In the following code
```cpp

#include <fstream>
#include <iostream>
#include <string>

#include <boost/network/protocol/http/client.hpp>
#include <boost/network/uri.hpp>

namespace http = boost::network::http;
namespace uri = boost::network::uri;

namespace
{

std::string get_filename(const uri::uri& url)
{
    std::string path = uri::path(url);
    std::size_t index = path.find_last_of('/');
    std::string filename = path.substr(index + 1);
    return filename.empty() ? "index.html" : filename;
}

} // namespace

int main(int argc, char **argv)
{
    if (argc != 2)
    {
        std::cerr << "Usage: " << argv[0] << " url" << std::endl;
        return 1;
    }

    http::client client;
    http::client::request request(argv[1]);
    request << boost::network::header("Connection", "close");
    http::client::response response = client.get(request);

    std::string filename = get_filename(request.uri());
    std::cout << "Saving to: " << filename << std::endl;
    std::ofstream ofs(filename.c_str());
    ofs << static_cast<std::string>(body(response)) << std::endl;

    return 0;
}
```
the code is stuck at reading response body. Attaching my gdb session:
```
(gdb) break wget.cpp:39
Breakpoint 1 at 0x418210: file wget.cpp, line 39.
(gdb) break wget.cpp:40
Breakpoint 2 at 0x418241: file wget.cpp, line 40.
[New Thread 0x7ffff582a700 (LWP 4094)]
[New Thread 0x7ffff5029700 (LWP 4095)]

Breakpoint 1, main (argc=2, argv=0x7fffffffe838) at wget.cpp:39
39	    std::cout << "Saving to: " << filename << std::endl;
(gdb) print filename
$1 = "index.html"
(gdb) next
Saving to: index.html
[Thread 0x7ffff582a700 (LWP 4094) exited]

Breakpoint 2, main (argc=2, argv=0x7fffffffe838) at wget.cpp:40
40	    std::ofstream ofs(filename.c_str());
(gdb) next
41	    ofs << static_cast<std::string>(body(response)) << std::endl;
(gdb) next
```

**Comment by robin92** [comment] 2015-03-16 20:20
up

**Comment by deanberris** [comment] 2015-03-17 00:01
Which URL are you trying to fix, can you print the headers (is it doing chunked transfer encoding), and is the server not closing the connection?

There are other ways around this, one is to use the version of 'get' that has a streaming body callback.

But I can't really debug this without knowing what the server is doing.

**Comment by robin92** [comment] 2015-03-17 16:54
@deanberris You can try any address you wish. I tried with local Python HTTP server as well as, eg. google or my personal website. Issue is always reproducible.

I'll check streaming get tommorow and post the results.

**Comment by ankurs47** [comment] 2015-04-27 09:16
It gets stuck with '-std=c++11' flag enabled.

**Comment by beniz** [comment] 2015-05-05 05:49
Experiencing the same issue with extremely simple code. Obviously, from my gdb trace, this the future not returning, hanging on a cond wait. So somehow, this could indicate that the request call (async ?) is not returning ? Nasty bug IMO...

**Comment by beniz** [comment] 2015-05-05 07:05
> There are other ways around this, one is to use the version of 'get' that has a streaming body callback.

So I tried the two examples from the bottom of https://github.com/cpp-netlib/cpp-netlib/blob/master/doc/reference/http_client.rst

None of them work for me: the connection to the server is not even made, which I assume has to do with the future return of get somehow.

Also, I did compile from source, but the simple_wget examples and the read_headers examples exe do fail with a file error, which at this stage is beyond the time I can allocate immediately.

However, I am available for helping resolve this. Another thread reports a mismatch between static compilation of cppnetlib against boost-1.54 while running with boost-1.55. I am using Ubuntu 15.04 and the version of boost the current cppnetlib package is linked against is lost in the ELF exe AFAIK.

**Comment by robin92** [comment] 2015-05-05 14:30
As far as my issue is concerned it is no longer reproducable with 2c4428275e2bd8a7718f1c2376d8660dc5357ca1
```cpp
#include <iostream>
#include <string>

#include <network/http/client.hpp>

namespace http = network::http;

int main(int argc, char **argv)
{
    http::client client;
    http::request request(network::uri {std::string(argv[1])});
    request.version("1.1");
    request.append_header("Connection", "Close");

    auto future_response = client.get(request);
    const auto response = future_response.get();
    std::cout << response.body() << std::endl;

    return 0;
}
```
I've tested the following code on http://google.com and local Python server. The former one requires to explicitly set http version.

Environment:
```
clang version 3.6.0 (tags/RELEASE_360/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```
```
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib64/libicuuc.so
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   regex
--   filesystem
-- C++ Compiler ID: Clang
-- C++ Flags: -std=c++14 -std=c++11 link flags: 
-- CPP-NETLIB options selected:
--   CPP-NETLIB_BUILD_SHARED_LIBS:      OFF	(Build cpp-netlib as shared libraries: OFF, ON)
--   CPP-NETLIB_BUILD_SINGLE_LIB:       OFF	(Build cpp-netlib into a single library: OFF, ON)
--   CPP-NETLIB_BUILD_TESTS:            ON	(Build the unit tests: ON, OFF)
--   CPP-NETLIB_BUILD_EXAMPLES:         ON	(Build the examples using cpp-netlib: ON, OFF)
--   CPP-NETLIB_ALWAYS_LOGGING:         OFF	(Allow cpp-netlib to log debug messages even in non-debug mode: ON, OFF)
--   CPP-NETLIB_DISABLE_LOGGING:        OFF	(Disable logging definitely, no logging code will be generated or compiled: ON, OFF)
--   CPP-NETLIB_DISABLE_LIBCXX:         ON	(Disable using libc++ when building with clang: ON, OFF)
--   CPP-NETLIB_DISABLE_FEATURE_TESTS:  OFF	(Disable the feature tests (which may use a network connection): ON, OFF)
-- CMake build options selected:
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
C++ Flags: -std=c++14 -std=c++11 -std=c++11 -ftemplate-depth=1024 link flags: 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/robin/Desktop/netlib/cpp-netlib/build
```

Also all the tests and available on this particular revision work out of the box in both release and debug mode.

**Comment by Sfinx** [comment] 2015-07-05 17:13
Just got this issue on ubuntu - the problem appears that all the code (including boost) need to be compiled with the same std=.

**Comment by redboltz** [comment] 2015-08-25 02:14
I'm experiencing the same problem.
It happens only when the cpp-netlib build with CMAKE_BUILD_TYPE=Release and simple_wget.cpp complies with -std=c++11 (or later) option.

### Environment:
#### cpp-netlib version:
0.11.1
https://github.com/cpp-netlib/cpp-netlib/tree/cpp-netlib-0.11.1-final

#### OS:
Linux arch 4.1.5-1-ARCH #1 SMP PREEMPT Tue Aug 11 15:41:14 CEST 2015 x86_64 GNU/Linux

#### Compiler:
gcc (GCC) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

clang version 3.6.2 (tags/RELEASE_362/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix

#### cpp-netlib build options:
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCPP-NETLIB_BUILD_TESTS=OFF -DCPP-NETLIB_BUILD_EXAMPLES=OFF ..

cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCPP-NETLIB_BUILD_TESTS=OFF -DCPP-NETLIB_BUILD_EXAMPLES=OFF ..

#### Boost version:
1.58.0

#### OpenSSL version:
1.0.2d

#### Target Source:
cpp-netlib/libs/network/example/simple_wget.cpp

#### Tested URL:
any. e.g. http://www.google.com/

#### Compile options:
clang++ -std=c++11 simple_wget.cpp -I/home/kondo/work/cpp-netlib/ -L/home/kondo/work/cpp-netlib/build/libs/ -lcppnetlib-uri -lcppnetlib-client-connections -lboost_system -lboost_thread -pthread -lssl -lcrypto

/home/kondo/work/cpp-netlib/ is the directory cpp-netlib is cloned.

**Comment by deanberris** [comment] 2015-08-25 05:43
Please build Boost with -std=c++11 as well. If you're still seeing the problem, please see whether the latest in 0.11-devel fixes it. If it doesn't, can you let me know? Thanks @redboltz

**Comment by redboltz** [comment] 2015-08-25 06:22
Hi @deanberris, thank you for your quick response. I built boost with -std=c++11 flag. I choose version 1.58.0. And then, I built cpp-netlib 0.11.1 with the boost libraries. 
However, the same issue occurred. I will check the latest 0.11-devel as soon as possible. 

Here is what I did:
```
./bootstrap
./b2 toolset=gcc cxxflags="-std=c++11"
```
During building boost, I got the following warnings due to -std=c++11 flags:
```
./boost/smart_ptr/shared_ptr.hpp:531:38: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
```
It's not a problem.

Then I built cpp-netlib.
```
cmake -DBOOST_ROOT=/home/kondo/work/boost/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCPP-NETLIB_BUILD_TESTS=OFF -DCPP-NETLIB_BUILD_EXAMPLES=OFF ..
```
I checked CMakeCache.txt, and found the following contents:

```
//No help, variable specified on the command line.
BOOST_ROOT:PATH=/home/kondo/work/boost/

//Boost atomic library (debug)
Boost_ATOMIC_LIBRARY_DEBUG:FILEPATH=/home/kondo/work/boost/stage/lib/libboost_atomic.a

//Boost atomic library (release)
Boost_ATOMIC_LIBRARY_RELEASE:FILEPATH=/home/kondo/work/boost/stage/lib/libboost_atomic.a
```

It seems that boost is correctly recognized by cpp-netlib.

Then I compiled the example.
```
g++ -std=c++11 simple_wget.cpp -I/home/kondo/work/cpp-netlib/ -I/home/kondo/work/boost/ -L/home/kondo/work/cpp-netlib/build/libs/network/src/ -L/home/kondo/work/boost/stage/lib/ -lcppnetlib-
uri -lcppnetlib-client-connections -lboost_system -lboost_thread -pthread -lssl -lcrypto
```
Then set LD_LIBRARY_PATH environment variable:
```
export LD_LIBRARY_PATH=/home/kondo/work/boost/stage/lib
```
Finally executed the compiled binary with URL.

I got the following output and program is stuck:
```
Saving to: index.html
```

**Comment by redboltz** [comment] 2015-08-25 06:32
I tested with https://github.com/cpp-netlib/cpp-netlib/commits/0.11-devel. Then I got the same issue.

I also tested as follows:

Compile simple_wget.cpp with -std=c++03 option, the issue wasn't reproduced.
Build cpp-netlib with -DCMAKE_BUILD_TYPE=Debug and compile simple_wget.cpp with -std=c++11 option, the issue wasn't reproduced.

**Comment by redboltz** [comment] 2015-08-25 07:00
I realized that cpp-netlib itself isn't compiled with -std=c++11 option.
After cmake configuration, I did 'make VERBOSE=1'.

'-std=c++11' option is not passed to g++ as follows:
```
[ 14%] Building CXX object libs/network/src/CMakeFiles/cppnetlib-client-connections.dir/client.cpp.o
cd /home/kondo/work/cpp-netlib/build/libs/network/src && /usr/bin/g++   -DBOOST_NETWORK_ENABLE_HTTPS -Wall -O3 -DNDEBUG -I/home/kondo/local/include -I/home/kondo/work/boost -I/home/kondo/work/cpp-netlib    -o CM
akeFiles/cppnetlib-client-connections.dir/client.cpp.o -c /home/kondo/work/cpp-netlib/libs/network/src/client.cpp
```

Is that OK?

**Comment by deanberris** [comment] 2015-08-25 08:01
No, that is not OK.

You should use `-DCMAKE_CXX_FLAGS=-std=c++11` if you want to build cpp-netlib 0.11.1 (or 0.11-devel) in C++11 mode.

**Comment by redboltz** [comment] 2015-08-26 01:09
I added -DCMAKE_CXX_FLAGS=-std=c++11, then simple_wget.cpp works fine.
I tested the following combination:

|boost|cpp-netlib|
|-----|----------|
|c++11|0.11-devel|
|c++11|cpp-netlib-0.11.1-final|
|c++03|0.11-devel|
|c++03|cpp-netlib-0.11.1-final|

All cases works fine. Thanks for your support!

I think that the issue is caused by Boost.Asio's ABI mismatch. It's not a Boost.Asio's problem. C++03 build of cpp-netlib and C++11 build of simple_wget.cpp could have different ABI but the same API. That is chosen by boost/asio/config.hpp. I sometimes forget about that because Boost.Asio is a header only library. But when we use a non header only library that uses Boost.Asio such as cpp-netlib, we need to care which ABI is used in the library.

Anyway, the issue is solved for me. Thanks again!

**Closed** 2015-09-04 20:27 UTC

**Comment by snap9** [comment] 2016-10-17 19:47
@robin92 @redboltz @deanberris I'm experiencing this issue on Visual Studio 2015. I don't know if the "-std=c++11" option is even available on Windows VS2015. Do you have any ideas?

**Comment by vasild** [comment] 2016-10-19 07:46
Hello,

from the above I gather that all of:

* boost
* cpp-netlib
* the program/library that uses cpp-netlib, lets name it A

must be compiled either in C++11 mode or not. That is - either all of them should use -std=c++11 or all of them should not. Is that correct?

Then the following issue arises - if one is implementing A that uses cpp-netlib internally and A is supposed to be compiled on the user's machine where the user has installed boost and cpp-netlib as a dependencies to A, then A should either be compiled in C++11 mode or not depending on how cpp-netlib and boost were compiled by the user's packaging system.

How could A's cmake system detect whether cpp-netlib and boost were compiled in C++11 mode, so that it can do the same?
