### ISSUE TITLE
VS2015 compile error -- conversion from netdb_errors to std::err_code

### ISSUE THREAD

**Issue by stevenawright** [cpp-netlib/cpp-netlib#616] opened 2016-03-11 03:36 UTC
Enviroment:
Windows 7 Professional Service Pack 1 -- 64 bit operating system
VS2015 Version 14.0.24720.00 Update 1
Compiling under Debug Win32 and Debug x64
Boost 1.60               -- into directory Boost_1_60_0
cpp-netlib v0.11.2    -- into directory CPP_NetLib_012

I copied Boost to its own directory.  Within Boost_1_60_0/boost there was not a network directory; so I copied from CPP_NetLib_012/boost/network to Boost_1_60_0/boost
also copied mime.hpp and network.hpp into Boost_1_60_0/boost.

Here is the source code for the client, pretty much out of the example:
# include "stdafx.h"
# include <boost/network/protocol/http/client.hpp>
# include <iostream>

int main(int argc, char *argv[])
{
    using namespace boost::network;

```
if (argc != 2)
{
    std::cout << "Usage: " << argv[0] << " [url]" << std::endl;
    return 1;
}

http::client client;
http::client::request request(argv[1]);
request << header("Connection", "close");
http::client::response response = client.get(request);
std::cout << body(response) << std::endl;

return 0;
```

}

I get a tonne of warnings, that are all the same:
      C4348 'boost::spirit::terminalboost::spirit::tag::ascii::char_::result_helper': redefinition of default parameter: parameter 3  Client_Netter   c:\blablabla\boost_1_60_0\boost\spirit\home\support\terminal.hpp    264 
      C4348 'boost::spirit::terminalboost::spirit::tag::ascii::char_::result_helper': redefinition of default parameter: parameter 4  Client_Netter   c:\blablabla\boost_1_60_0\boost\spirit\home\support\terminal.hpp    264 

This is the error message:
Error   C2446   ':': no conversion from 'boost::asio::error::netdb_errors' to 'const std::error_code'   Client_Netter   c:\blablabla\boost_1_60_0\boost\network\protocol\http\client\connection\async_normal.hpp    158 

Async_normal.hpp looks like this:
    } else {
      set_errors(ec ? ec : asio::error::host_not_found);
      boost::iterator_range<const char*> range;
      if (callback) callback(range, ec);
    }

Any insight would be appreciated.

**Comment by deanberris** [comment] 2016-03-11 05:32
You also need to build the libraries -- they're in `libs/network/src`.

I recommend you build/install with CMake as how we've documented it. You can generate a VS project and depend on cpp-netlib that way.

**Comment by philippludwig** [comment] 2016-03-23 14:47
I just would like to add that I have the exact same problems when I try to build the libraries using CMake and Visual Studio.

Furthermore, msbuild throws tons of LNk2019 errors, complaining about unresolved SSL functions, i.e. "_SSL_CTX_get_ex_data".

I assume that CMake does not properly create the Visual Studio solution files and that the SSL libraries have to be added somewhere. Of course this could also be related to the windows OpenSSL distribution that I chose since I have no idea which is the correct one for cpp-netlib, as this is not discussed in the documentation.

**Comment by MMOSimca** [comment] 2016-04-07 08:56
philippludwig, your problem is not the same as the first post in this ticket. However, I do have some experience with your problem; it is a very common issue for tools relying on OpenSSL on Windows.

My preferred solution (there may be others):
1. Download the latest "non-Light" version of OpenSSL for Win32 from https://slproweb.com/products/Win32OpenSSL.html.
2. Download the latest "non-Light" version of OpenSSL for Win64 from the same site.
3. Install them both to different folders (I think the defaults are fine - one folder is named OpenSSL-Win32 and the other is named OpenSSL-Win64).
4. Add their 'includes' and 'libs' directories to your PATH (or to your Visual Studio defaults or whatever your preferred method is).

**Comment by kiwidoggie** [comment] 2016-04-09 15:54
I currently am having the same issue as @stevenawright , installing the OpenSSL binaries did not help at all. It fails on building server_request_parsers_impl.cpp

**Comment by deanberris** [comment] 2016-04-18 04:50
So cpp-netlib 0.11.2 isn't built by default with C++11 -- you will have to build Boost and cpp-netlib in C++11 mode.

**Comment by ytong3** [comment] 2016-04-21 14:13
I had the same issue when #include "boost/network/protocol/http.hpp" in my code. I was referencing a successful build of cpp-netlib 0.12 by the way. I wonder do we have a solution yet? Thanks.

**Comment by deanberris** [comment] 2016-04-21 14:59
I don't get this -- the code should work just fine. I suspect since the project is being built with C++11 mode, it's trying to look for the conversion from an ASIO error code to a standard error code. The only way this will happen with Boost is if you build it in C++11 mode (and install it in C++11 mode). Now 0.11.2 doesn't default to being built with C++11 turned on, so you'd need to fix that when you build the cpp-netlib library. I don't know how to do this with MSVC, but it may need to be set when doing '-DCMAKE_CXX_FLAGS=' on the command-line when running CMake to generate the project.

If there's a flag similar to '-std=c++11' when building Boost or your project, you'd need to set it for all -- Boost, cpp-netlib, and your project. If you *don't* want C++11 features, you're going to need to explicitly disable C++11 mode from *all* these projects (or your whole solution).

Does that help?

**Comment by MMOSimca** [comment] 2016-04-21 16:02
I think this is caused by the project not including the files from the built-in asio library. It is looking for those asio files in boost, and it isn't going to find the ones it wants.

Make sure you are including 'cpp-netlib\deps\asio\asio\include' or something similar in your VC++ includes directory paths. Note that this path is not properly set by the CMake configuration right now.

**Comment by ytong3** [comment] 2016-04-21 17:22
@deanberris  It seems that MSVC (Visual Studio 15) doesn't need a flag to turn C++11 on. It is always in C++11 mode (well, welcome to MSVC...) see link here https://msdn.microsoft.com/en-us/library/fwkeyyhe.aspx

On the other hand, building with the -std=c++11 flag on Linux always works like a charm.

@MMOSimca  you are right. Actually, it darned on me that I could take a look at the example project (for instance http_client) that comes with the source to figure out the appropriate include and link directories. Indeed, the http_client project generated by cmake has 'cpp-netlib\deps\asio\asio\include among the project's include directories. 

Anyway, I ended up including that director. The previous error about cannot convert errors went away, but now I got other conversion errors: 

Error	C2664	'void std::_Func_class<_Ret,const boost::iterator_range<const boost::network::uri::uri::value_type *> &,const std::error_code &>::operator ()(const boost::iterator_range<const boost::network::uri::uri::value_type *> &,const std::error_code &) const': **cannot convert argument 1 from 'boost::iterator_range<std::_Array_const_iterator<_Ty,1024>>' to 'const boost::iterator_range<const boost::network::uri::uri::value_type *> &'	hello_world_client**	

C:\foo\bar\cpp-netlib-0.12.0-final\boost\network\protocol\http\client\connection\async_normal.hpp	351	

Building the http_client example gave me the same errors.

Any help is appreciated!

**Comment by TapanGIT** [comment] 2016-04-27 01:46
I am also facing same error mentioned in the above comment while building the the http_client example.

some other, related errors.

Error	C2664	'void std::_Func_class<_Ret,const boost::iterator_range<const boost::network::uri::uri::value_type *> &,const std::error_code &>::operator ()(const boost::iterator_range<const boost::network::uri::uri::value_type *> &,const std::error_code &) const': cannot convert argument 1 from 'boost::iterator_range<std::_Array_const_iterator<_Ty,1024>>' to 'const boost::iterator_range<const boost::network::uri::uri::value_type *> &'


Error	C2664	'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::append(std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>,std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>)': cannot convert argument 1 from 'std::_Array_iterator<_Ty,1024>' to 'const std::basic_string<char,std::char_traits<char>,std::allocator<char>> &'

Please help in resolving it.

**Comment by ytong3** [comment] 2016-04-27 13:22
@TapanGIT  FYI, I ended up using 0.11 version, which compiled just fine. I suspected it was because the MSVC's implementation of std library that caused the problem.

**Comment by TapanGIT** [comment] 2016-04-27 19:20
@ytong3 Could you please provide the information regarding the boost library version that has been used for compilation ?

**Comment by ytong3** [comment] 2016-04-27 19:33
@TapanGIT the latest boost_1_60_0 it was.

**Comment by TapanGIT** [comment] 2016-05-01 02:14
@ytong3 Thanks

**Comment by wapxmas** [comment] 2016-05-01 08:41
Error while compiling rss_reader, Boost 1_60_0:

Error	C2664	'void std::_Func_class<_Ret,const boost::iterator_range<const boost::network::uri::uri::value_type *> &,const std::error_code &>::operator ()(const boost::iterator_range<const boost::network::uri::uri::value_type *> &,const std::error_code &) const': cannot convert argument 1 from 'boost::iterator_range<std::_Array_const_iterator<_Ty,1024>>' to 'const boost::iterator_range<const boost::network::uri::uri::value_type *> &'	rss_reader

**Comment by glynos** [comment] 2016-05-01 12:18
I think I see what is happening here: the iterator type of the buffers we use internally don't match with those specified in the callback interface. VS2015 seems to be stricter here than all the other compilers we test with. It should be relatively straightforward to fix, but I don't have access to the VS2015 compiler.

Would anyone be willing to take this on, and to send in a PR?

**Comment by kiwidoggie** [comment] 2016-05-01 14:27
@glynos https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx

**Comment by glynos** [comment] 2016-05-02 08:15
Thanks, @kiwidoggie. I am aware of it's availability, but I use Linux as my development environment.

**Comment by kiwidoggie** [comment] 2016-05-02 13:13
I mean I can test a PR for you, but I also am on Linux (currently) and used the VM's for x-compiling with msvc.

**Comment by deanberris** [comment] 2016-05-10 09:50
@kiwidoggie -- can you try making a fix for this?

**Comment by snap9** [comment] 2016-05-21 18:37
I'm having these exact same problems. cpp-netlib-0.12.0. Boost 1_60_0.
@glynos You can get VS2015 for free on Microsoft's page. It's right here: https://www.visualstudio.com/en-us/products/visual-studio-express-vs.aspx (I clicked on Download under "Express for Desktop").

**Comment by JamesAMD** [comment] 2016-07-16 19:19
@ytong3 
Strange... Including that directory didn't help with the conversion error...

**Comment by JamesAMD** [comment] 2016-07-16 19:51
Forcefully converting boost::asio::error::netdb_errors to std::error_code
```
template<typename TEnum>
  std::error_code error(TEnum const& ec) {
      return std::make_error_code((std::errc)ec);
  }
```
seems to have fixed the type conversion error (which, admittedly, doesn't seem right) but new 12 errors came up complaining about the lack of operator== for std::error_category and boost::system_error_category, std::error_code and boost::asio::error::***_errors.

Would love to be able to use cpp-netlib on VS2015......

**Comment by deanberris** [comment] 2016-07-18 07:24
The changes involved to make this work I think are going to be really invasive.

FWIW, @glynos has made the latest in the master branch use the Boost.Asio library again (the experiment with stand-alone ASIO didn't quite work out in 0.12.0).

@JamesAMD -- if you can try using the latest in master, and work perhaps with @glynos to get some changes to make the library work in Windows, I would very much appreciate this. As it stands, I have no access to a Windows machine and I don't think I will have enough time to try and set one up just for cpp-netlib development.

That being said, I'd be happy to review pull requests to fix this.

**Comment by glynos** [comment] 2016-10-14 06:06
What is the current status of this? Does the 0.13-release branch work?

**Comment by glynos** [comment] 2016-12-04 15:55
cpp-netlib 0.13-release builds and tests succeed on MSVC 2015, so I will close this.

**Closed** 2016-12-04 15:56 UTC
Labels: Windows
